# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Louis Cruz
email: lac323@cornell.edu
description: >
             I eat only meat and I think about a lot of things.           
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://loucru1.github.io" # the base hostname & protocol for your site
twitter_username: louiscomments
github_username:  loucru1
tag_page: /tags/


# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag

author: Louis Cruz
twitter:
  username: louiscomments

# travis-ci
exclude: [vendor]
sudo: false
